// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://grgimvmfjynmhqofvsyg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdyZ2ltdm1manlubWhxb2Z2c3lnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1NzkxOTYsImV4cCI6MjA2NzE1NTE5Nn0._s6q8DH1rdO9_P7WUWlWxbe9WdWkZm7oe9FemkLWVVs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});